INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STENCH', 'Stench', 'The stench may cause the target to flinch.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DRIZZLE', 'Drizzle', 'The Pokemon makes it rain if it appears in battle.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SPEEDBOOST', 'Speed Boost', 'Its Speed stat is gradually boosted.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('BATTLEARMOR', 'Battle Armor', 'The Pokemon is protected against critical hits.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STURDY', 'Sturdy', 'It cannot be knocked out with one hit.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DAMP', 'Damp', 'Prevents the use of self-destructing moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('LIMBER', 'Limber', 'The Pokemon is protected from paralysis.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SANDVEIL', 'Sand Veil', 'Boosts the Pokemon''s evasion in a sandstorm.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STATIC', 'Static', 'Contact with the Pokemon may cause paralysis.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('VOLTABSORB', 'Volt Absorb', 'Restores HP if hit by an Electric-type move.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('WATERABSORB', 'Water Absorb', 'Restores HP if hit by a Water-type move.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('OBLIVIOUS', 'Oblivious', 'Prevents it from becoming infatuated.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('CLOUDNINE', 'Cloud Nine', 'Eliminates the effects of weather.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('COMPOUNDEYES', 'Compound Eyes', 'The Pokemon''s accuracy is boosted.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('INSOMNIA', 'Insomnia', 'Prevents the Pokemon from falling asleep.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('COLORCHANGE', 'Color Change', 'Changes the Pokemon''s type to the foe''s move.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('IMMUNITY', 'Immunity', 'Prevents the Pokemon from getting poisoned.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FLASHFIRE', 'Flash Fire', 'It powers up Fire-type moves if it''s hit by one.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SHIELDDUST', 'Shield Dust', 'Blocks the added effects of attacks taken.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('OWNTEMPO', 'Own Tempo', 'Prevents the Pokemon from becoming confused.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SUCTIONCUPS', 'Suction Cups', 'Negates all moves that force switching out.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('INTIMIDATE', 'Intimidate', 'Lowers the foe''s Attack stat.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SHADOWTAG', 'Shadow Tag', 'Prevents the foe from escaping.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ROUGHSKIN', 'Rough Skin', 'Inflicts damage to the foe on contact.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('WONDERGUARD', 'Wonder Guard', 'Only super-effective moves will hit.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('LEVITATE', 'Levitate', 'Gives full immunity to all Ground-type moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('EFFECTSPORE', 'Effect Spore', 'Contact may poison or cause paralysis or sleep.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SYNCHRONIZE', 'Synchronize', 'Passes a burn, poison, or paralysis to the foe.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('CLEARBODY', 'Clear Body', 'Prevents other Pokemon from lowering its stats.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('NATURALCURE', 'Natural Cure', 'All status problems heal when it switches out.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('LIGHTNINGROD', 'Lightning Rod', 'Draws in all Electric-type moves to up Sp. Attack.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SERENEGRACE', 'Serene Grace', 'Boosts the likelihood of added effects appearing.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SWIFTSWIM', 'Swift Swim', 'Boosts the Pokemon''s Speed in rain.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('CHLOROPHYLL', 'Chlorophyll', 'Boosts the Pokemon''s Speed in sunshine.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ILLUMINATE', 'Illuminate', 'Raises the likelihood of meeting wild Pokemon.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TRACE', 'Trace', 'The Pokemon copies a foe''s Ability.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('HUGEPOWER', 'Huge Power', 'Raises the Pokemon''s Attack stat.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('POISONPOINT', 'Poison Point', 'Contact with the Pokemon may poison the attacker.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('INNERFOCUS', 'Inner Focus', 'The Pokemon is protected from flinching.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MAGMAARMOR', 'Magma Armor', 'Prevents the Pokemon from becoming frozen.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('WATERVEIL', 'Water Veil', 'Prevents the Pokemon from getting a burn.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MAGNETPULL', 'Magnet Pull', 'Prevents Steel-type Pokemon from escaping.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SOUNDPROOF', 'Soundproof', 'Gives full immunity to all sound-based moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('RAINDISH', 'Rain Dish', 'The Pokemon gradually regains HP in rain.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SANDSTREAM', 'Sand Stream', 'The Pokemon summons a sandstorm in battle.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PRESSURE', 'Pressure', 'The Pokemon raises the foe''s PP usage.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('THICKFAT', 'Thick Fat', 'Ups resistance to Fire- and Ice-type moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('EARLYBIRD', 'Early Bird', 'The Pokemon awakens quickly from sleep.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FLAMEBODY', 'Flame Body', 'Contact with the Pokemon may burn the attacker.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('RUNAWAY', 'Run Away', 'Enables a sure getaway from wild Pokemon.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('KEENEYE', 'Keen Eye', 'Prevents other Pokemon from lowering accuracy.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('HYPERCUTTER', 'Hyper Cutter', 'Prevents other Pokemon from lowering Attack stat.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PICKUP', 'Pickup', 'The Pokemon may pick up items.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TRUANT', 'Truant', 'Pokemon can''t attack on consecutive turns.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('HUSTLE', 'Hustle', 'Boosts the Attack stat, but lowers accuracy.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('CUTECHARM', 'Cute Charm', 'Contact with the Pokemon may cause infatuation.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PLUS', 'Plus', 'Ups Sp. Atk if another Pokemon has Plus or Minus.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MINUS', 'Minus', 'Ups Sp. Atk if another Pokemon has Plus or Minus.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FORECAST', 'Forecast', 'Castform transforms with the weather.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STICKYHOLD', 'Sticky Hold', 'Protects the Pokemon from item theft.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SHEDSKIN', 'Shed Skin', 'The Pokemon may heal its own status problems.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('GUTS', 'Guts', 'Boosts Attack if there is a status problem.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MARVELSCALE', 'Marvel Scale', 'Ups Defense if there is a status problem.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('LIQUIDOOZE', 'Liquid Ooze', 'Damages attackers using any draining move.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('OVERGROW', 'Overgrow', 'Powers up Grass-type moves in a pinch.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('BLAZE', 'Blaze', 'Powers up Fire-type moves in a pinch.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TORRENT', 'Torrent', 'Powers up Water-type moves in a pinch.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SWARM', 'Swarm', 'Powers up Bug-type moves in a pinch.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ROCKHEAD', 'Rock Head', 'Protects the Pokemon from recoil damage.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DROUGHT', 'Drought', 'Turns the sunlight harsh if it is in battle.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ARENATRAP', 'Arena Trap', 'Prevents the foe from fleeing.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('VITALSPIRIT', 'Vital Spirit', 'Prevents the Pokemon from falling asleep.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('WHITESMOKE', 'White Smoke', 'Prevents other Pokemon from lowering its stats.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PUREPOWER', 'Pure Power', 'Raises the Pokemon''s Attack stat.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SHELLARMOR', 'Shell Armor', 'The Pokemon is protected against critical hits.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('AIRLOCK', 'Air Lock', 'Eliminates the effects of weather.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TANGLEDFEET', 'Tangled Feet', 'Raises evasion if the Pokemon is confused.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MOTORDRIVE', 'Motor Drive', 'Raises Speed if hit by an Electric-type move.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('RIVALRY', 'Rivalry', 'Deals more damage to a foe of the same gender.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STEADFAST', 'Steadfast', 'Raises Speed each time the Pokemon flinches.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SNOWCLOAK', 'Snow Cloak', 'Raises evasion in a hailstorm.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('GLUTTONY', 'Gluttony', 'Encourages the early use of a held Berry.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ANGERPOINT', 'Anger Point', 'Maxes Attack after taking a critical hit.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('UNBURDEN', 'Unburden', 'Raises Speed if a held item is used.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('HEATPROOF', 'Heatproof', 'Weakens the power of Fire-type moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SIMPLE', 'Simple', 'The Pokemon is prone to wild stat changes.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DRYSKIN', 'Dry Skin', 'Reduces HP if it is hot. Water restores HP.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DOWNLOAD', 'Download', 'Adjusts power according to a foe''s defenses.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('IRONFIST', 'Iron Fist', 'Boosts the power of punching moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('POISONHEAL', 'Poison Heal', 'Restores HP if the Pokemon is poisoned.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ADAPTABILITY', 'Adaptability', 'Powers up moves of the same type.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SKILLLINK', 'Skill Link', 'Increases the frequency of multi-strike moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('HYDRATION', 'Hydration', 'Heals status problems if it is raining.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SOLARPOWER', 'Solar Power', 'In sunshine, Sp. Atk is boosted but HP decreases.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('QUICKFEET', 'Quick Feet', 'Boosts Speed if there is a status problem.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('NORMALIZE', 'Normalize', 'All the Pokemon''s moves become the Normal type.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SNIPER', 'Sniper', 'Powers up moves if they become critical hits.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MAGICGUARD', 'Magic Guard', 'The Pokemon only takes damage from attacks.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('NOGUARD', 'No Guard', 'Ensures attacks by or against the Pokemon land.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STALL', 'Stall', 'The Pokemon moves after all other Pokemon do.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TECHNICIAN', 'Technician', 'Powers up the Pokemon''s weaker moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('LEAFGUARD', 'Leaf Guard', 'Prevents problems with status in sunny weather.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('KLUTZ', 'Klutz', 'The Pokemon can''t use any held items.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MOLDBREAKER', 'Mold Breaker', 'Moves can be used regardless of Abilities.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SUPERLUCK', 'Super Luck', 'Heightens the critical-hit ratios of moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('AFTERMATH', 'Aftermath', 'Damages the attacker landing the finishing hit.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ANTICIPATION', 'Anticipation', 'Senses a foe''s dangerous moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FOREWARN', 'Forewarn', 'Determines what moves a foe has.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('UNAWARE', 'Unaware', 'Ignores any stat changes in the Pokemon.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TINTEDLENS', 'Tinted Lens', 'Powers up "not very effective" moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FILTER', 'Filter', 'Reduces damage from super-effective attacks.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SLOWSTART', 'Slow Start', 'Temporarily halves Attack and Speed.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SCRAPPY', 'Scrappy', 'Enables moves to hit Ghost-type Pokemon.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STORMDRAIN', 'Storm Drain', 'Draws in all Water-type moves to up Sp. Attack.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ICEBODY', 'Ice Body', 'The Pokemon gradually regains HP in a hailstorm.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SOLIDROCK', 'Solid Rock', 'Reduces damage from super-effective attacks.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SNOWWARNING', 'Snow Warning', 'The Pokemon summons a hailstorm in battle.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('HONEYGATHER', 'Honey Gather', 'The Pokemon may gather Honey from somewhere.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FRISK', 'Frisk', 'The Pokemon can check a foe''s held item.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('RECKLESS', 'Reckless', 'Powers up moves that have recoil damage.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MULTITYPE', 'Multitype', 'Changes type to match the held Plate.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FLOWERGIFT', 'Flower Gift', 'Powers up party Pokemon when it is sunny.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('BADDREAMS', 'Bad Dreams', 'Reduces a sleeping foe''s HP.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PICKPOCKET', 'Pickpocket', 'Steals an item when hit by another Pokemon.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SHEERFORCE', 'Sheer Force', 'Removes added effects to increase move damage.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('CONTRARY', 'Contrary', 'Makes stat changes have an opposite effect.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('UNNERVE', 'Unnerve', 'Makes the foe nervous and unable to eat Berries.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DEFIANT', 'Defiant', 'When its stats are lowered its Attack increases.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DEFEATIST', 'Defeatist', 'Lowers stats when HP becomes half or less.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('CURSEDBODY', 'Cursed Body', 'May disable a move used on the Pokemon.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('HEALER', 'Healer', 'May heal an ally''s status conditions.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FRIENDGUARD', 'Friend Guard', 'Reduces damage done to allies.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('WEAKARMOR', 'Weak Armor', 'Physical attacks lower Defense and raise Speed.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('HEAVYMETAL', 'Heavy Metal', 'Doubles the Pokemon''s weight.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('LIGHTMETAL', 'Light Metal', 'Halves the Pokemon''s weight.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MULTISCALE', 'Multiscale', 'Reduces damage when HP is full.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TOXICBOOST', 'Toxic Boost', 'Powers up physical attacks when poisoned.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FLAREBOOST', 'Flare Boost', 'Powers up special attacks when burned.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('HARVEST', 'Harvest', 'May create another Berry after one is used.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TELEPATHY', 'Telepathy', 'Anticipates an ally''s attack and dodges it.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MOODY', 'Moody', 'Raises one stat and lowers another.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('OVERCOAT', 'Overcoat', 'Protects the Pokemon from damage from weather.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('POISONTOUCH', 'Poison Touch', 'May poison targets when a Pokemon makes contact.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('REGENERATOR', 'Regenerator', 'Restores a little HP when withdrawn from battle.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('BIGPECKS', 'Big Pecks', 'Protects from Defense-lowering attacks.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SANDRUSH', 'Sand Rush', 'Boosts the Pokemon''s Speed in a sandstorm.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('WONDERSKIN', 'Wonder Skin', 'Makes status-changing moves more likely to miss.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ANALYTIC', 'Analytic', 'Boosts move power when the Pokemon moves last.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ILLUSION', 'Illusion', 'Comes out disguised as the Pokemon in back.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('IMPOSTER', 'Imposter', 'It transforms itself into the Pokemon it is facing.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('INFILTRATOR', 'Infiltrator', 'Passes through the foe''s barrier and strikes.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MUMMY', 'Mummy', 'Contact with this Pokemon spreads this Ability.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MOXIE', 'Moxie', 'Boosts Attack after knocking out any Pokemon.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('JUSTIFIED', 'Justified', 'Raises Attack when hit by a Dark-type move.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('RATTLED', 'Rattled', 'Some move types scare it and boost its Speed.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MAGICBOUNCE', 'Magic Bounce', 'Reflects status-changing moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SAPSIPPER', 'Sap Sipper', 'Boosts Attack when hit by a Grass-type move.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PRANKSTER', 'Prankster', 'Gives priority to a status move.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SANDFORCE', 'Sand Force', 'Boosts certain moves'' power in a sandstorm.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('IRONBARBS', 'Iron Barbs', 'Inflicts damage to the Pokemon on contact.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ZENMODE', 'Zen Mode', 'Changes the Pokemon''s shape when HP is halved.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('VICTORYSTAR', 'Victory Star', 'Boosts the accuracy of its allies and itself.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TURBOBLAZE', 'Turboblaze', 'Moves can be used regardless of Abilities.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TERAVOLT', 'Teravolt', 'Moves can be used regardless of Abilities.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('AROMAVEIL', 'Aroma Veil', 'Protects against attacks that limit move choices.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FLOWERVEIL', 'Flower Veil', 'Protects Grass-type allies from stat/status effects.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('CHEEKPOUCH', 'Cheek Pouch', 'Restores HP as well when the Pokemon eats a Berry.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PROTEAN', 'Protean', 'It changes type to that of the move it''s about to use.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FURCOAT', 'Fur Coat', 'Halves the damage from physical moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MAGICIAN', 'Magician', 'Steals the held item of a Pokemon it hits.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('BULLETPROOF', 'Bulletproof', 'Protects the Pokemon from some ball and bomb moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('COMPETITIVE', 'Competitive', 'Sharply boosts Sp. Atk when a stat is lowered.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STRONGJAW', 'Strong Jaw', 'Boosts the power of biting moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('REFRIGERATE', 'Refrigerate', 'Normal-type moves become Ice-type and powered up.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SWEETVEIL', 'Sweet Veil', 'Prevents itself and allies from falling asleep.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STANCECHANGE', 'Stance Change', 'Changes between Blade and Shield Forme with attacks.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('GALEWINGS', 'Gale Wings', 'Flying-type moves gain priority when its HP is full.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MEGALAUNCHER', 'Mega Launcher', 'Powers up aura and pulse moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('GRASSPELT', 'Grass Pelt', 'Boosts the Defense stat on Grassy Terrain.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SYMBIOSIS', 'Symbiosis', 'Passes its held item to an ally that has used theirs.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TOUGHCLAWS', 'Tough Claws', 'Powers up moves that make direct contact.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PIXILATE', 'Pixilate', 'Normal-type moves become Fairy-type and powered up.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('GOOEY', 'Gooey', 'Contact with it lowers the attacker''s Speed stat.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('AERILATE', 'Aerilate', 'Normal-type moves become Flying-type and power up.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PARENTALBOND', 'Parental Bond', 'Parent and child each attacks.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DARKAURA', 'Dark Aura', 'Powers up each Pokemon''s Dark-type moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FAIRYAURA', 'Fairy Aura', 'Powers up each Pokemon''s Fairy-type moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('AURABREAK', 'Aura Break', 'Reverses "Aura" Abilities to weaken affected moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PRIMORDIALSEA', 'Primordial Sea', 'Changes the weather to nullify Fire-type moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DESOLATELAND', 'Desolate Land', 'Changes the weather to nullify Water-type moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DELTASTREAM', 'Delta Stream', 'Alters weather to remove Flying-type''s weaknesses.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STAMINA', 'Stamina', 'Boosts Defense when hit by an attack.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('WIMPOUT', 'Wimp Out', 'Cowardly switches out if its HP becomes half or less.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('EMERGENCYEXIT', 'Emergency Exit', 'Switches out if its HP becomes half or less.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('WATERCOMPACTION', 'Water Compaction', 'Sharply ups Defense when hit by a Water-type move.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MERCILESS', 'Merciless', 'Its attacks are critical hits when it is poisoned.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SHIELDSDOWN', 'Shields Down', 'Its shell breaks if its HP becomes half or less.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STAKEOUT', 'Stakeout', 'Deals doubles damage to a target''s replacement.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('WATERBUBBLE', 'Water Bubble', 'Weakens incoming Fire-type moves and prevents burns.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STEELWORKER', 'Steelworker', 'Powers up Steel-type moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('BERSERK', 'Berserk', 'Ups Sp. Atk if a hit makes its HP half or less.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SLUSHRUSH', 'Slush Rush', 'Boosts the Pokemon''s Speed stat in a hailstorm.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('LONGREACH', 'Long Reach', 'Uses moves without making contact with the target.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('LIQUIDVOICE', 'Liquid Voice', 'Its sound-based moves become Water-type.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TRIAGE', 'Triage', 'Gives priority to a healing move.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('GALVANIZE', 'Galvanize', 'Normal-type moves become Electric-type and powered.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SURGESURFER', 'Surge Surfer', 'Doubles Speed on Electric Terrain.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SCHOOLING', 'Schooling', 'Forms a powerful school while it has a lot of HP.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DISGUISE', 'Disguise', 'Its shroud protects it from an attack just once.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('BATTLEBOND', 'Battle Bond', 'Defeating a foe lets it become Ash-Greninja.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('POWERCONSTRUCT', 'Power Construct', 'Changes with other Cells if HP becomes half or less.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('CORROSION', 'Corrosion', 'It can poison Steel- and Poison-type targets.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('COMATOSE', 'Comatose', 'It''s always drowsing, and attacks without waking.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('QUEENLYMAJESTY', 'Queenly Majesty', 'Makes foes unable to use priority attacks.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('INNARDSOUT', 'Innards Out', 'Damages an attacker that lands the finishing hit.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DANCER', 'Dancer', 'Repeats another Pokemon''s dance move immediately.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('BATTERY', 'Battery', 'Powers up ally Pokemon''s special moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FLUFFY', 'Fluffy', 'Resists contact damage but weaker to Fire-type.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DAZZLING', 'Dazzling', 'Makes foes unable to use priority attacks.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SOULHEART', 'Soul-Heart', 'Boosts Sp. Atk each time a Pokemon faints.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TANGLINGHAIR', 'Tangling Hair', 'Contact with it lowers the attacker''s Speed.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('RECEIVER', 'Receiver', 'Copies the Ability of a defeated ally.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('POWEROFALCHEMY', 'Power of Alchemy', 'Copies the Ability of a defeated ally.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('BEASTBOOST', 'Beast Boost', 'Boosts its best stat each time it deals a KO.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('RKSSYSTEM', 'RKS System', 'Its type matches the memory disc it holds.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ELECTRICSURGE', 'Electric Surge', 'Turns the ground into Electric Terrain.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PSYCHICSURGE', 'Psychic Surge', 'Turns the ground into Psychic Terrain.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MISTYSURGE', 'Misty Surge', 'Turns the ground into Misty Terrain.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('GRASSYSURGE', 'Grassy Surge', 'Turns the ground into Grassy Terrain.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('FULLMETALBODY', 'Full Metal Body', 'Prevents other Pokemon from lowering its stats.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SHADOWSHIELD', 'Shadow Shield', 'Resists damage while its HP is full.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PRISMARMOR', 'Prism Armor', 'Reduces damage from super-effective attacks.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('NEUROFORCE', 'Neuroforce', 'Powers up moves that are super-effective.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('INTREPIDSWORD', 'Intrepid Sword', 'Boosts Attack when entering a battle.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DAUNTLESSSHIELD', 'Dauntless Shield', 'Boosts Defense when entering a battle.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('LIBERO', 'Libero', 'It changes type to that of the move it''s about to use.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('BALLFETCH', 'Ball Fetch', 'Retrieves the first thrown Poke Ball if it failed.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('COTTONDOWN', 'Cotton Down', 'Scatters Speed-lowering cotton fluff when hit.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PROPELLERTAIL', 'Propeller Tail', 'This Pokemon''s moves cannot be redirected.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MIRRORARMOR', 'Mirror Armor', 'Bounces back stat-lowering effects.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('GULPMISSILE', 'Gulp Missile', 'Catches prey via Surf or Dive, spits it out when hit.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STALWART', 'Stalwart', 'This Pokemon''s moves cannot be redirected.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STEAMENGINE', 'Steam Engine', 'Boosts Speed drastically if hit by a Fire or Water move.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PUNKROCK', 'Punk Rock', 'Powers up own sound moves. Resists other sound moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SANDSPIT', 'Sand Spit', 'Creates a sandstorm when hit by an attack.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ICESCALES', 'Ice Scales', 'Halves the damage taken from special moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('RIPEN', 'Ripen', 'Ripens Berries and doubles their effect.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ICEFACE', 'Ice Face', 'Blocks a physical hit, but the ice head breaks.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('POWERSPOT', 'Power Spot', 'Just being next to the Pokemon powers up moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('MIMICRY', 'Mimicry', 'Changes type depending on the terrain.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('SCREENCLEANER', 'Screen Cleaner', 'On entering battle, clears effects of Reflect, etc.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('STEELYSPIRIT', 'Steely Spirit', 'Powers up ally Pokemon''s Steel-type moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PERISHBODY', 'Perish Body', 'Both Pokemon faint 3 turns after taking a contact hit.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('WANDERINGSPIRIT', 'Wandering Spirit', 'Swaps Abilities with contact-making Pokemon.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('GORILLATACTICS', 'Gorilla Tactics', 'Boosts Attack, but allows only one move to be used.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('NEUTRALIZINGGAS', 'Neutralizing Gas', 'Nullifies the effects of all other Abilities.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('PASTELVEIL', 'Pastel Veil', 'Protects the Pokemon and its allies from poisoning.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('HUNGERSWITCH', 'Hunger Switch', 'Changes between Full Belly and Hangry Mode each turn.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('QUICKDRAW', 'Quick Draw', 'Enables the Pokemon to move first occasionally.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('UNSEENFIST', 'Unseen Fist', 'The Pokemon''s contact moves ignore protections.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('CURIOUSMEDICINE', 'Curious Medicine', 'Removes all allies'' stat changes on joining battle.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('TRANSISTOR', 'Transistor', 'Powers up Electric-type moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('DRAGONSMAW', 'Dragon''s Maw', 'Powers up Dragon-type moves.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('CHILLINGNEIGH', 'Chilling Neigh', 'When knocking out a target, raises Attack.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('GRIMNEIGH', 'Grim Neigh', 'When knocking out a target, raises Sp. Atk.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ASONECHILLINGNEIGH', 'As One', 'Combines Unnerve and Chilling Neigh Abilities.');
INSERT INTO Ability (a_name, a_i_name, a_description) VALUES ('ASONEGRIMNEIGH', 'As One', 'Combines Unnerve and Grim Neigh Abilities.');