use cs3380;
drop table if exists Type_Status_Immunity;
drop table if exists Type_Weakness;
drop table if exists Type_Immunity;
drop table if exists Type_Resist;
drop table if exists Move_Type;
drop table if exists Move_Status_Effects;
drop table if exists Item_Status_Effects;
drop table if exists Pokemon_Item_Evolution;
drop table if exists Pokemon_Item_Form_Change;
drop table if exists Pokemon_Form;
drop table if exists Pokemon_Move;
drop table if exists Pokemon_Ability;
drop table if exists Pokemon_Evolution;
drop table if exists Pokemon_Egg;
drop table if exists Pokemon_Type;
drop table if exists Status;
drop table if exists Move;
drop table if exists EggGroup;
drop table if exists Item;
drop table if exists Type;
drop table if exists Ability;
drop table if exists Pokemon;
create table Pokemon (pokedex_number INTEGER, form_id INTEGER, p_name VARCHAR(64), p_generation INTEGER, p_hp INTEGER,p_atk INTEGER, p_def INTEGER,p_satk INTEGER, p_sdef INTEGER,p_sped INTEGER, p_description VARCHAR(256), PRIMARY KEY(pokedex_number,form_id));
create table Ability (a_name VARCHAR(64) PRIMARY KEY, a_i_name VARCHAR(64), a_description VARCHAR(128));
create table Type (t_name VARCHAR(64) PRIMARY KEY);
create table Item (i_name VARCHAR(64) PRIMARY KEY, i_i_name VARCHAR(64), i_teaches VARCHAR(64), i_description VARCHAR(256));
create table EggGroup (e_name VARCHAR(64) PRIMARY KEY);
create table Move (m_i_name VARCHAR(64) PRIMARY KEY, m_name VARCHAR(64), m_category VARCHAR(64), m_power INTEGER, m_accuracy VARCHAR(64), m_range VARCHAR(64), m_description VARCHAR(256));
create table Status (s_name varchar(64) PRIMARY KEY, s_volatile varchar(64), s_duration varchar(64), s_description varchar(256));
create table Pokemon_Type (pokedex_number INTEGER, form_id INTEGER, t_name varchar(64) REFERENCES Type, FOREIGN KEY(pokedex_number, form_id) REFERENCES Pokemon, PRIMARY KEY(pokedex_number, form_id, t_name));
create table Pokemon_Egg (pokedex_number INTEGER, form_id INTEGER, e_name varchar(64) REFERENCES EggGroup, FOREIGN KEY (pokedex_number,form_id) REFERENCES Pokemon(pokedex_number,form_id), PRIMARY KEY(pokedex_number,form_id,e_name));
create table Pokemon_Evolution (pre_evo INTEGER, pre_f_id INTEGER, post_evo INTEGER, post_f_id INTEGER, FOREIGN KEY(pre_evo,pre_f_id) REFERENCES Pokemon(pokedex_number,form_id), FOREIGN KEY(post_evo,post_f_id) REFERENCES Pokemon(pokedex_number,form_id), PRIMARY KEY(pre_evo,pre_f_id,post_evo,post_f_id));
create table Pokemon_Ability (pokedex_number INTEGER, form_id INTEGER, a_name varchar(64) REFERENCES Ability, FOREIGN KEY (pokedex_number, form_id) REFERENCES Pokemon, PRIMARY KEY(pokedex_number, form_id, a_name));
create table Pokemon_Move (pokedex_number INTEGER, form_id INTEGER, m_name varchar(64) REFERENCES Move, FOREIGN KEY (pokedex_number, form_id) REFERENCES Pokemon, PRIMARY KEY(pokedex_number,form_id,m_name));
create table Pokemon_Form (pokedex_number INTEGER, pre_f_id INTEGER, post_f_id INTEGER, FOREIGN KEY(pokedex_number,pre_f_id) REFERENCES Pokemon(pokedex_number,form_id), FOREIGN KEY(pokedex_number,post_f_id)REFERENCES Pokemon(pokedex_number,form_id), PRIMARY KEY(pokedex_number,pre_f_id,post_f_id));
create table Pokemon_Item_Form_Change (pokedex_number INTEGER, pre_f_id INTEGER, post_f_id INTEGER, i_name varchar(64) REFERENCES Item, FOREIGN KEY(pokedex_number, pre_f_id) REFERENCES Pokemon(pokedex_number, form_id), FOREIGN KEY(pokedex_number,post_f_id)REFERENCES Pokemon(pokedex_number,form_id), PRIMARY KEY(pokedex_number,pre_f_id, post_f_id,i_name));
create table Pokemon_Item_Evolution (pre_pokedex_number INTEGER, pre_f_id INTEGER, i_name varchar(64) REFERENCES Item, post_pokedex_number INTEGER, post_f_id INTEGER, FOREIGN KEY(pre_pokedex_number, pre_f_id)  REFERENCES Pokemon (pokedex_number, form_id), FOREIGN KEY(post_pokedex_number, post_f_id)  REFERENCES Pokemon (pokedex_number, form_id), PRIMARY KEY (pre_pokedex_number,pre_f_id,i_name,post_pokedex_number,post_f_id));
create table Item_Status_Effects (i_name varchar(64) REFERENCES Item, s_name varchar(64) REFERENCES Status, PRIMARY KEY (i_name,s_name));
create table Move_Status_Effects (m_name varchar(64) REFERENCES Move, s_name varchar(64) REFERENCES Status, chance INTEGER,PRIMARY KEY (m_name,s_name));
create table Move_Type (m_name varchar(64) REFERENCES Move, t_name varchar(64) REFERENCES Type, PRIMARY KEY (m_name,t_name));
create table Type_Resist (resist_defender varchar(64) REFERENCES Type(t_name), resist_attacker varchar(64) REFERENCES Type(t_name), PRIMARY KEY (resist_defender,resist_attacker));
create table Type_Immunity (immune_defender varchar(64) REFERENCES Type(t_name), immune_attacker varchar(64) REFERENCES Type(t_name), PRIMARY KEY (immune_defender,immune_attacker));
create table Type_Weakness (weakness_defender varchar(64) REFERENCES Type(t_name), weakness_attacker varchar(64) REFERENCES Type(t_name), PRIMARY KEY (weakness_defender,weakness_attacker));
create table Type_Status_Immunity (t_name varchar(64) REFERENCES Type, s_name varchar(64) REFERENCES Status, PRIMARY KEY (s_name,t_name));