INSERT into Item_Status_Effects VALUES ('ANTIDOTE','Poison');
INSERT into Item_Status_Effects VALUES ('ANTIDOTE','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('ASPEARBERRY','Frozen');
INSERT into Item_Status_Effects VALUES ('PERSIMBERRY','Confused');
INSERT into Item_Status_Effects VALUES ('YELLOWFLUTE','Confused');
INSERT into Item_Status_Effects VALUES ('AWAKENING','Sleep');
INSERT into Item_Status_Effects VALUES ('BLUEFLUTE','Sleep');
INSERT into Item_Status_Effects VALUES ('BURNHEAL','Burn');
INSERT into Item_Status_Effects VALUES ('CHERIBERRY','Paralysis');
INSERT into Item_Status_Effects VALUES ('CHESTOBERRY','Sleep');
INSERT into Item_Status_Effects VALUES ('ICEHEAL','Frozen');
INSERT into Item_Status_Effects VALUES ('REDFLUTE','Infatuated');
INSERT into Item_Status_Effects VALUES ('MENTALHERB','Infatuated');
INSERT into Item_Status_Effects VALUES ('MENTALHERB','Encore');
INSERT into Item_Status_Effects VALUES ('MENTALHERB','Taunt');
INSERT into Item_Status_Effects VALUES ('PARALYZEHEAL','Paralysis');
INSERT into Item_Status_Effects VALUES ('PECHABERRY','Poison');
INSERT into Item_Status_Effects VALUES ('PECHABERRY','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('POKEFLUTE','Sleep');
INSERT into Item_Status_Effects VALUES ('RAWSTBERRY','Burn');
INSERT into Item_Status_Effects VALUES ('FULLHEAL','Poison');
INSERT into Item_Status_Effects VALUES ('FULLHEAL','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('FULLHEAL','Paralysis');
INSERT into Item_Status_Effects VALUES ('FULLHEAL','Burn');
INSERT into Item_Status_Effects VALUES ('FULLHEAL','Sleep');
INSERT into Item_Status_Effects VALUES ('FULLHEAL','Frozen');
INSERT into Item_Status_Effects VALUES ('FULLHEAL','Confused');
INSERT into Item_Status_Effects VALUES ('FULLRESTORE','Poison');
INSERT into Item_Status_Effects VALUES ('FULLRESTORE','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('FULLRESTORE','Paralysis');
INSERT into Item_Status_Effects VALUES ('FULLRESTORE','Burn');
INSERT into Item_Status_Effects VALUES ('FULLRESTORE','Sleep');
INSERT into Item_Status_Effects VALUES ('FULLRESTORE','Frozen');
INSERT into Item_Status_Effects VALUES ('FULLRESTORE','Confused');
INSERT into Item_Status_Effects VALUES ('BIGMALASADA','Poison');
INSERT into Item_Status_Effects VALUES ('BIGMALASADA','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('BIGMALASADA','Paralysis');
INSERT into Item_Status_Effects VALUES ('BIGMALASADA','Burn');
INSERT into Item_Status_Effects VALUES ('BIGMALASADA','Sleep');
INSERT into Item_Status_Effects VALUES ('BIGMALASADA','Frozen');
INSERT into Item_Status_Effects VALUES ('BIGMALASADA','Confused');
INSERT into Item_Status_Effects VALUES ('CASTELIACONE','Poison');
INSERT into Item_Status_Effects VALUES ('CASTELIACONE','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('CASTELIACONE','Paralysis');
INSERT into Item_Status_Effects VALUES ('CASTELIACONE','Burn');
INSERT into Item_Status_Effects VALUES ('CASTELIACONE','Sleep');
INSERT into Item_Status_Effects VALUES ('CASTELIACONE','Frozen');
INSERT into Item_Status_Effects VALUES ('CASTELIACONE','Confused');
INSERT into Item_Status_Effects VALUES ('HEALPOWDER','Poison');
INSERT into Item_Status_Effects VALUES ('HEALPOWDER','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('HEALPOWDER','Paralysis');
INSERT into Item_Status_Effects VALUES ('HEALPOWDER','Burn');
INSERT into Item_Status_Effects VALUES ('HEALPOWDER','Sleep');
INSERT into Item_Status_Effects VALUES ('HEALPOWDER','Frozen');
INSERT into Item_Status_Effects VALUES ('HEALPOWDER','Confused');
INSERT into Item_Status_Effects VALUES ('LUMBERRY','Poison');
INSERT into Item_Status_Effects VALUES ('LUMBERRY','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('LUMBERRY','Paralysis');
INSERT into Item_Status_Effects VALUES ('LUMBERRY','Burn');
INSERT into Item_Status_Effects VALUES ('LUMBERRY','Sleep');
INSERT into Item_Status_Effects VALUES ('LUMBERRY','Frozen');
INSERT into Item_Status_Effects VALUES ('LUMBERRY','Confused');
INSERT into Item_Status_Effects VALUES ('LAVACOOKIE','Poison');
INSERT into Item_Status_Effects VALUES ('LAVACOOKIE','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('LAVACOOKIE','Paralysis');
INSERT into Item_Status_Effects VALUES ('LAVACOOKIE','Burn');
INSERT into Item_Status_Effects VALUES ('LAVACOOKIE','Sleep');
INSERT into Item_Status_Effects VALUES ('LAVACOOKIE','Frozen');
INSERT into Item_Status_Effects VALUES ('LAVACOOKIE','Confused');
INSERT into Item_Status_Effects VALUES ('LUMIOSEGALETTE','Poison');
INSERT into Item_Status_Effects VALUES ('LUMIOSEGALETTE','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('LUMIOSEGALETTE','Paralysis');
INSERT into Item_Status_Effects VALUES ('LUMIOSEGALETTE','Burn');
INSERT into Item_Status_Effects VALUES ('LUMIOSEGALETTE','Sleep');
INSERT into Item_Status_Effects VALUES ('LUMIOSEGALETTE','Frozen');
INSERT into Item_Status_Effects VALUES ('LUMIOSEGALETTE','Confused');
INSERT into Item_Status_Effects VALUES ('OLDGATEAU','Poison');
INSERT into Item_Status_Effects VALUES ('OLDGATEAU','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('OLDGATEAU','Paralysis');
INSERT into Item_Status_Effects VALUES ('OLDGATEAU','Burn');
INSERT into Item_Status_Effects VALUES ('OLDGATEAU','Sleep');
INSERT into Item_Status_Effects VALUES ('OLDGATEAU','Frozen');
INSERT into Item_Status_Effects VALUES ('OLDGATEAU','Confused');
INSERT into Item_Status_Effects VALUES ('PEWTERCRUNCHIES','Poison');
INSERT into Item_Status_Effects VALUES ('PEWTERCRUNCHIES','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('PEWTERCRUNCHIES','Paralysis');
INSERT into Item_Status_Effects VALUES ('PEWTERCRUNCHIES','Burn');
INSERT into Item_Status_Effects VALUES ('PEWTERCRUNCHIES','Sleep');
INSERT into Item_Status_Effects VALUES ('PEWTERCRUNCHIES','Frozen');
INSERT into Item_Status_Effects VALUES ('PEWTERCRUNCHIES','Confused');
INSERT into Item_Status_Effects VALUES ('RAGECANDYBAR','Poison');
INSERT into Item_Status_Effects VALUES ('RAGECANDYBAR','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('RAGECANDYBAR','Paralysis');
INSERT into Item_Status_Effects VALUES ('RAGECANDYBAR','Burn');
INSERT into Item_Status_Effects VALUES ('RAGECANDYBAR','Sleep');
INSERT into Item_Status_Effects VALUES ('RAGECANDYBAR','Frozen');
INSERT into Item_Status_Effects VALUES ('RAGECANDYBAR','Confused');
INSERT into Item_Status_Effects VALUES ('SHALOURSABLE','Poison');
INSERT into Item_Status_Effects VALUES ('SHALOURSABLE','Badly Poisoned');
INSERT into Item_Status_Effects VALUES ('SHALOURSABLE','Paralysis');
INSERT into Item_Status_Effects VALUES ('SHALOURSABLE','Burn');
INSERT into Item_Status_Effects VALUES ('SHALOURSABLE','Sleep');
INSERT into Item_Status_Effects VALUES ('SHALOURSABLE','Frozen');
INSERT into Item_Status_Effects VALUES ('SHALOURSABLE','Confused');