INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ATTRACT','Infatuated',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('WRAP','Bound',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('CURSE','Cursed',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('LEECHSEED','Seeded',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ENCORE','Encore',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('YAWN','Drowsy',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('EMBARGO','Embargo',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('HEALBLOCK','Heal Block',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('MEANLOOK','Can''t Escape',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('BLOCK','Can''t Escape',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('NIGHTMARE','Nightmare',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('PERISHSONG','Perish Song',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('TAUNT','Taunt',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('TELEKINESIS','Telekinesis',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('AQUARING','Aqua Ring',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('INGRAIN','Ingrained',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('MAGICCOAT','Magic Coat',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('MAGNETRISE','Magnetic Levitation',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('PROTECT','Protected',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('DETECT','Protected',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SUBSTITUTE','Substitute',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SAFEGUARD','Safeguarded',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('THRASH','Thrashing',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('BURNUP','Type Change',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('CONVERSION','Type Change',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('CONVERSION2','Type Change',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FORESTSCURSE','Type Change',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('MAGICPOWDER','Type Change',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('REFLECTTYPE','Type Change',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ROOST','Type Change',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SOAK','Type Change',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('TRANSFORM','Type Change',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('TRICKORTREAT','Type Change',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('CHATTER','Confused',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('CONFUSION','Confused',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('PSYBEAM','Confused',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SIGNALBEAM','Confused',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('DIZZYPUNCH','Confused',20);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ROCKCLIMB','Confused',20);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('WATERPULSE','Confused',20);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('DYNAMICPUNCH','Confused',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('CONFUSERAY','Confused',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SUPERSONIC','Confused',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SWEETKISS','Confused',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('TEETERDANCE','Confused',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SWAGGER','Confused',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FLATTER','Confused',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('OUTRAGE','Confused',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('THRASH','Confused',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('PETALDANCE','Confused',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('AIRSLASH','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ASTONISH','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('BITE','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('BONECLUB','Flinch',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('DARKPULSE','Flinch',20);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('DRAGONRUSH','Flinch',20);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('EXTRASENSORY','Flinch',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FAKEOUT','Flinch',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FIREFANG','Flinch',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('HEADBUTT','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('HEARTSTAMP','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('HYPERFANG','Flinch',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ICEFANG','Flinch',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ICICLECRASH','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('IRONHEAD','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('NEEDLEARM','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ROCKSLIDE','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ROLLINGKICK','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SKYATTACK','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SNORE','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('STEAMROLLER','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('STOMP','Flinch',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('THUNDERFANG','Flinch',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('TWISTER','Flinch',20);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('WATERFALL','Flinch',20);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ZENHEADBUTT','Flinch',20);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('DARKVOID','Sleep',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('GRASSWHISTLE','Sleep',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('HYPNOSIS','Sleep',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('LOVELYKISS','Sleep',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('REST','Sleep',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SING','Sleep',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SLEEPPOWDER','Sleep',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SPORE','Sleep',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('RELICSONG','Sleep',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('TRIATTACK','Burn',7);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('BLAZEKICK','Burn',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('EMBER','Burn',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FIREBLAST','Burn',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FIREFANG','Burn',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FIREPUNCH','Burn',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FLAMETHROWER','Burn',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FLAMEWHEEL','Burn',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FLAREBLITZ','Burn',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('HEATWAVE','Burn',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('BLUEFLARE','Burn',20);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SACREDFIRE','Burn',50);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SEARINGSHOT','Burn',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ICEBURN','Burn',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('LAVAPLUME','Burn',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SCALD','Burn',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('INFERNO','Burn',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('WILLOWISP','Burn',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('STEAMERUPTION','Burn',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('TRIATTACK','Frozen',7);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('BLIZZARD','Frozen',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ICEBEAM','Frozen',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ICEFANG','Frozen',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ICEPUNCH','Frozen',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('POWDERSNOW','Frozen',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('TRIATTACK','Paralysis',7);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('BOLTSTRIKE','Paralysis',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('THUNDERFANG','Paralysis',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('THUNDERPUNCH','Paralysis',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('THUNDERSHOCK','Paralysis',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('VOLTTACKLE','Paralysis',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('BODYSLAM','Paralysis',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('BOUNCE','Paralysis',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('DISCHARGE','Paralysis',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('DRAGONBREATH','Paralysis',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FORCEPALM','Paralysis',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('FREEZESHOCK','Paralysis',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('LICK','Paralysis',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SPARK','Paralysis',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('THUNDER','Paralysis',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('GLARE','Paralysis',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('STUNSPORE','Paralysis',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('THUNDERWAVE','Paralysis',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('ZAPCANNON','Paralysis',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('TOXICSPIKES','Poison',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('CROSSPOISON','Poison',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('POISONTAIL','Poison',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SLUDGEWAVE','Poison',10);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('GUNKSHOT','Poison',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('POISONJAB','Poison',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('POISONSTING','Poison',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SLUDGE','Poison',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SLUDGEBOMB','Poison',30);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('SMOG','Poison',40);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('POISONGAS','Poison',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('POISONPOWDER','Poison',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('TOXIC','Badly Poisoned',100);
INSERT into Move_Status_Effects (m_name,s_name,chance) VALUES ('POISONFANG','Badly Poisoned',30);