INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Sleep','false','1-3 turns','The Pokemon falls asleep and cannot attack.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Paralysis','false','Until cured','The Pokemon has a chance to freeze up, unable to move for a turn.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Burn','false','Until cured','The Pokemon''s attack is halved, and it takes damaged each turn.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Frozen','false','20% chance to thaw each turn','The Pokemon is frozen solid and cannot move.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Poison','false','Until cured','The Pokemon is poisoned, taking damaged each turn.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Badly Poisoned','false','Until cured','The Pokemon is badly poisoned, taking damage each turn. The amount of damage increases each time.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Bound','true','4-5 turns','The Pokemon is bound and cannot switch out. It takes damage each turn.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Can''t Escape','true','Until cured','The Pokemon cannot run from battle.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Confused','true','2-5 turns','A confused Pokemon has a chance to damage itself instead of attacking.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Cursed','true','Until cured','The Pokemon is cursed, taking damage each turn.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Drowsy','true','1 turn','The Pokemon is sleepy, and will fall asleep next turn.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Embargo','true','5 turns','The Pokemon cannot use items.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Encore','true','3 turns','The Pokemon can only use the last move it took.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Heal Block','true','5 turns','The Pokemon cannot restore health.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Identified','true','Until cured','Removes immunities of ghost types.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Infatuated','true','Until cured','The Pokemon is in love and may become immobilized by it, unable to attack.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Seeded','true','Until cured','Seeds on the Pokemon leech its health, healing the opponent.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Nightmare','true','While asleep','The Pokemon will take damage every turn it is asleep.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Perish Song','true','3 turns','The Pokemon will faint in 3 turns.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Taunt','true','2 turns','The Pokemon can only use damaging moves.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Telekinesis','true','3 turns','The Pokemon is held in the air, making all moves against it hit.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Aqua Ring','true','9-16 turns','The Pokemon regains health each turn.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Ingrained','true','Until cured','Removes immunities of ghost types.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Magic Coat','true','1 turn','Reflects certain Status moves back at the opponent.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Magnetic Levitation','true','Until cured','Pokemon rises from the ground, gaining immunity from ground type attacks.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Protected','true','1 turn','The Pokemon is protected from the next attack.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Substitute','true','Until destroyed','The Pokemon sets up a dummy, which takes damage in its place.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Safeguarded','true','5 turns','The Pokemon is protected from non-volatile Status and confusion.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Thrashing','true','2-3 turns','The Pokemon can only use Thrash for the duration, becoming confused afterward.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Flinch','true','1 turn','The Pokemon flinches, and cannot attack.');
INSERT into Status (s_name,s_volatile,s_duration,s_description) VALUES ('Type Change','true','Until cured','The Pokemon''s type changes, or it gains an additional type for the duration.');